flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef service fill:#e6e6e6,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a
    classDef meta   fill:#f5f5ff,stroke:#9999cc,color:#333

    subgraph ctx["Graph"]
        direction LR
        ctx_meta["claimant: :Paula_Walker\ngraphSubject: :Paula_Walker\nshape: pshapes:ContactInfoShape"]:::meta
    end

    n679aafec7a4b[":Paula_Walker\n(Person)"]:::person
    nf09cdc092d01("Paula"):::lit
    n1addbe4f2eea("Retired"):::lit
    n770cb4b8e788("+19165550172"):::lit

    n679aafec7a4b -->|"GivenName"| nf09cdc092d01
    n679aafec7a4b -->|"OrganizationName"| n1addbe4f2eea
    n679aafec7a4b -->|"TelephoneNumber"| n770cb4b8e788
