%% ContextCategory: context:FamilyMember
flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef grp    fill:#d4edda,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a
    classDef meta   fill:#f5f5ff,stroke:#9999cc,color:#333

    subgraph ctx["Context"]
        direction LR
        ctx_meta["name: Family\ncategory: FamilyMember\nassertedBy: :Self\nsubject: :Paula_Walker\ndyad: paula(familymember)paula (3)"]:::meta
    end

    nf4296ab13de4[":Paula_Walker\n(Person)"]:::person
    n80cfbc8a171f("Paula"):::lit
    nf805b31afe73("Walker"):::lit

    nf4296ab13de4 -->|"GivenName"| n80cfbc8a171f
    nf4296ab13de4 -->|"FamilyName"| nf805b31afe73
