%% ContextCategory: context:Person
flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef grp    fill:#d4edda,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a

    n166b15bd501b[":Bob_Johnson\n(Person)"]:::person
    nfd9cae67f749("Fav drink: oat milk cappuccino"):::lit

    n166b15bd501b -->|"ent00000048"| nfd9cae67f749
