%% ContextCategory: context:Person
flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef grp    fill:#d4edda,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a

    n19c34148fc05[":Bob_Bob_Network\n(SocialNetwork)"]
    n89768dce3f8b["::Self"]
    n166b15bd501b[":Bob_Johnson\n(Person)"]:::person
    n366e62c829a6("Bob"):::lit
    nc277ef27e417("Johnson"):::lit

    n19c34148fc05 -->|"hasMember"| n89768dce3f8b
    n166b15bd501b -->|"GivenName"| n366e62c829a6
    n166b15bd501b -->|"FamilyName"| nc277ef27e417
    n166b15bd501b -->|"hasSocialNetwork"| n19c34148fc05
