%% ContextCategory: context:Group
flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef grp    fill:#d4edda,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a

    nbb363374209c[":Address_BHS\n(PostalAddress)"]
    nf1d742f069a6("123 Sleepy Hollow"):::lit
    n7b4917dd18a0("Paradise"):::lit
    nb4d90646dc47("CA"):::lit
    n44655699a947("95969"):::lit
    n1e88ebe9436d("USA"):::lit
    ne0c3ba92f1db[":Self\n(Person)"]:::person
    nb946460103c5("+15108149999"):::lit
    ndc040ae651ee("awalker@gmail.com"):::lit

    nbb363374209c -->|"StreetAddress"| nf1d742f069a6
    nbb363374209c -->|"CityName"| n7b4917dd18a0
    nbb363374209c -->|"StateName"| nb4d90646dc47
    nbb363374209c -->|"PostalCode"| n44655699a947
    nbb363374209c -->|"CountryName"| n1e88ebe9436d
    ne0c3ba92f1db -->|"designated by"| nbb363374209c
    ne0c3ba92f1db -->|"TelephoneNumber"| nb946460103c5
    ne0c3ba92f1db -->|"EmailAddress"| ndc040ae651ee
