%% ContextCategory: context:Group
flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef grp    fill:#d4edda,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a

    n1f280731bedf[":BHS_Group\n(Group)"]:::grp
    n89768dce3f8b["::Self"]
    ncea94215aa38["::Bob_Johnson"]

    n1f280731bedf -->|"hasMember"| n89768dce3f8b
    n1f280731bedf -->|"hasMember"| ncea94215aa38
