%% ContextCategory: context:Company
flowchart TD
    classDef person fill:#fffacd,stroke:#aaa,color:#333
    classDef grp    fill:#d4edda,stroke:#aaa,color:#333
    classDef org    fill:#cce5ff,stroke:#aaa,color:#333
    classDef lit    fill:none,stroke:none,font-style:italic,color:#2a7a2a

    ne0c3ba92f1db[":Self\n(Person)"]:::person
    n43c20fb0b237("+15108149999"):::lit

    ne0c3ba92f1db -->|"TelephoneNumber"| n43c20fb0b237
